### ISSUE TITLE
Allow to pass binded socket via fd: 0

### ISSUE THREAD

**Issue by jirutka** [tailhook/lithos#11]
Some programs (e.g. `java`) support starting on demand from xinetd daemon that binds socket on behalf of the program and passes it to the program using file descriptor 0, i.e. STDIN.

Unfortunately `fd: 0` cannot be used in Lithos:

```yaml
tcp-ports:
  8080:
    fd: 0
    host: 0.0.0.0
    reuse-addr: true
```

```sh
$ lithos_tree
thread 'main' panicked at 'Stdio file descriptors must be configured with respective methods instead of passing fd 0 to `file_descritor()`', .../github.com-1ecc6299db9ec823/unshare-0.2.0/src/fds.rs:33:13
```

`unshare` crate explicitly checks if the given fd is greater than 2 and panics when it’s not (see [fds.rs:32](https://github.com/tailhook/unshare/blob/v0.2.0/src/fds.rs#L32-L36)).

Could you please make it work even for fd 0?

**Comment by tailhook** [comment]
Fixed in master, but not released yet. Can you test ``v0.15.3-3-ge665852`` from master/testing?

**Comment by jirutka** [comment]
It works! Thank you for the fix and very fast response! 😺

**Comment by tailhook** [comment]
By the way, how do you configure java to accept file descriptor? I've used to think Java doesn't support that sort of very unix'ish things.

**Comment by jirutka** [comment]
JDK does provide a limited support for this unix feature – it can inherit socket passed via file descriptor 0, see [System.inheritedChannel()](https://docs.oracle.com/javase/9/docs/api/java/lang/System.html#inheritedChannel--). It’s not specified in docs, but the socket must be in blocking mode, it doesn’t work with non-blocking socket based on my experiments.

However, it seems that it’s quite unknown feature among Java developers. I guess that socket passing is too low-level and too simple thing for enterprisy Java guys…

For example [Jetty](https://www.eclipse.org/jetty/) servlet engine includes support for inherited channel, it’s documented as a way to run with (x)inetd. I wrote a simple library for Spring Boot – [spring-boot-servlet-inherit-channel](https://github.com/jirutka/spring-boot-servlet-inherit-channel) – to configure embedded Jetty to use inherited channel.
