### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by rsdy** [tailhook/lithos#7]
```
% sudo ./example_configs.sh 
[sudo] password for a: 
Copying examples/py into the system
WARNING: This Command will remove /etc/lithos from the system
... hopefully you run this in a virtual machine
... but let you think for 10 seconds
10 \r9 \r8 \r7 \r6 \r5 \r4 \r3 \r2 \r1 \r0 \rOkay proceeding...
building file list ... done

sent 188 bytes  received 11 bytes  398.00 bytes/sec
total size is 309  speedup is 1.55
Config /home/a/proj/lithos/vagga.yaml cannot be read: Error parsing config /home/a/proj/lithos/vagga.yaml: /home/a/proj/lithos/vagga.yaml:89:7: Parse Error: Expected scalar, sequence or mapping, got Anchor
```

Tested with vagga versions both `master` and `0.6.2`

**Comment by tailhook** [comment]
Hm, it works for me, with vagga `v0.6.1-77-gd72e45d` which is pretty old :) And there is no such thing as vagga `0.6.2` the current stable is 0.6.1. But I admit that the config might not work with 0.6.1. Hopefully, we'll release v0.7.0 in the next few days. 

You're probably talking about lithos 0.6.2, right ?

Do you run this thing in a vagrant? The `Vagrantfile` lying in this repository installs vagga from vagga-testing. You may want to try `apt-get update`, `apt-get install vagga` to upgrade it.

**Comment by tailhook** [comment]
By the way this is definitely an issue with the version of vagga used. So showing ``vagga --version`` would be helpful.

**Comment by rsdy** [comment]
That's correct, I confused the versions. However, when I do `vagga --version`, I just get:
```
% vagga --version
Usage:
    vagga [OPTIONS] [COMMAND] [ARGS ...]
vagga: Unknown option --version
```

When I build lithos from tag `v0.6.5` and vagga compiled from tag `v0.6.1`, I get the same results.

Unfortunately I can't use vagrant to test this. I tried an Arch VM.

**Comment by tailhook** [comment]
Interesting. Maybe `--version` appeared after vagga `v0.6.1`.  Can you use vagga from master? Do you use packages for aur for installing vagga? I think `vagga-bin` is more recent than `vagga` despite what you see in AUR package list, because `vagga-bin` always fetches latest version (and there is no way to update such packages, AFAIK on AUR)

**Comment by rsdy** [comment]
Thanks for pointing me to AUR. I never realised I had an ancient version installed through that, and PATH got mixed up. Works well now.
